# Pipeline for VIROME analyses of NOMIS & ENSEMBLE metaG datasets
#
# Example call: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --conda-prefix ${CONDA_PREFIX}/pipeline --cores 1 -rpn

##############################
# MODULES
import os, re
import glob
import pandas as pd


##############################
# CONFIG
# can be overwritten by using --configfile <path to config> when calling snakemake
# configfile: "config/config.yaml"

include:
    "rules/init.smk"


##############################
# TARGETS & RULES

# List of (main) targets to be created
TARGETS = []

# Viral identity
if "identity" in STEPS:
    include:
        "rules/viral_detection.smk"
    include:
        "rules/recA.smk"
    TARGETS += [
        "status/viral_detection.done",
        "status/recA.done"
    ]

if "phamb" in STEPS:
    include:
        "rules/vibrant_checkv.smk"
    include:
        "rules/vamb.smk"
    include:
        "rules/phamb.smk"
    TARGETS += [
        "status/vibrant_checkv.done",
        "status/vamb.done",
        "status/phamb.done",
    ]

if "final_map" in STEPS:
    include:
        "rules/final_checkv.smk"
    TARGETS += [
        "status/final_checkv.done"
    ]

# Taxonomy
if "taxonomy" in STEPS:
    include:
        "rules/imgvr3.smk"
    TARGETS += [
        "status/imgvr3.done"
    ]

# Depolymerases
if "depolymerase" in STEPS:
    include:
        "rules/depolymerase.smk"
    TARGETS += [
        "status/depolymerase.done"
    ]

# Quality check
if "checkv" in STEPS:
    include:
        "rules/checkv.smk"
    TARGETS += [
        "status/checkv.done"
    ]

# Phage-host interactions
if "phist" in STEPS:
    include:
        "rules/phist.smk"
    TARGETS += [
        "status/phist.done"
    ]

if "spacepharer" in STEPS:
    include:
        "rules/spacepharer.smk"
    TARGETS += [
        "status/spacepharer.done"
    ]

# Consensus phage-host
if "consensus" in STEPS:
    include:
        "rules/consensus.smk"
    TARGETS += [
        "status/consensus.done"
    ]

# AMR
if "amr" in STEPS:
    include:
        "rules/amr.smk"
    TARGETS += [
        "status/AMR.done"
    ]

# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    input:
        TARGETS

