# Pipeline for VIROME analyses of NOMIS & ENSEMBLE metaG datasets
#
# Example call: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --conda-prefix ${CONDA_PREFIX}/pipeline --cores 1 -rpn

##############################
# MODULES
import os, re
import glob
import pandas as pd


##############################
# CONFIG
# can be overwritten by using --configfile <path to config> when calling snakemake
# configfile: "config/config.yaml"

include:
    "rules/init.smk"


##############################
# TARGETS & RULES

# List of (main) targets to be created
TARGETS = []

# Viral identity
if "identity" in STEPS:
    include:
        "rules/viral_detection.smk"
    TARGETS += [
        "status/viral_detection.done"
    ]

# Taxonomy
if "taxonomy" in STEPS:
    include:
        "rules/imgvr3.smk"
    TARGETS += [
        "status/imgvr3.done"
    ]

# Quality check
if "checkv" in STEPS:
    include:
        "rules/checkv.smk"
    TARGETS += [
        "status/checkv.done"
    ]

# Phage-host interactions
if "phist" in STEPS:
    include:
        "rules/phist.smk"
    TARGETS += [
        "status/phist.done"
    ]

if "spacepharer" in STEPS:
    include:
        "rules/spacepharer.smk"
    TARGETS += [
        "status/spacepharer.done"
    ]

# AMR
if "amr" in STEPS:
    include:
        "rules/amr.smk"
    TARGETS += [
        "status/AMR.done"
    ]

# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    input:
        TARGETS

