############################################################
# STEPS

# Steps to be done
# steps: ["imp"]  # RUN THIS FIRST and launch IMP3 outside of the workflow

# Next the following steps should be run
# steps: ["identity", "taxonomy", "checkv", "phist", "spacepharer", "consensus", "amr"]
steps: ["identity", "phamb"]

############################################################
# INPUT

# Directory from where the Snakefile is run, i.e. the Github repo:
work_dir: "/work/projects/nomis/assemblies/viromes"

# Directory where the data is stored:
data_dir: "/work/projects/nomis/assemblies"

# Directory where the sample reads are stored:
reads_dir: "/work/projects/nomis/preprocessed_reads"

# Directory where the results should be:
results_dir: "/work/projects/nomis/assemblies/virome_results"

# Directory where the conda environments are:
env_dir: "/work/projects/nomis/assemblies/viromes/envs"

# # Directory with the sample FAA files:
# faa_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/vibrant_output"

# Directory with the IMGVR3 database:
db_dir: "/work/projects/nomis/tools/IMGVR3"

# # Directory with the gene coverages:
# cov_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/rockforest_results/coverage"

# # Directory with all the MAGs of interest
# mags_dir: "/mnt/data/sbusi/viruses/results/mags"

############################################################
# TOOLS 

##############################
# Identity workflow, i.e. to identify phages etc. 
vibrant:
  threads: 12
  db: "/work/projects/nomis/tools/vibrant/VIBRANT"

checkv:
  db: "/work/projects/nomis/tools/checkv/checkv-db-v1.0"  # UPDATE for ESB-compute-01 or litcrit
  threads: 4

vamb:
  threads: 4
  contigID: "_contig"
  length: 100
  minfasta: 1000

checkm:
  threads: 12

dvf:
  threads: 6
  length: 2000
  path: "/work/projects/nomis/assemblies/viromes/submodules/DeepVirFinder/dvf.py"

prodigal:
  threads: 6

hmmer:
  threads: 8

phamb:
  threads: 6
  run_RF: "/work/projects/nomis/assemblies/viromes/submodules/phamb/workflows/mag_annotation/scripts/run_RF.py"

##############################
# Coverage #
coverm:
  threads: 24
  bigmem_threads: 12
  tmp_dir: "/scratch/users/sbusi/tmp"

bwa:
  threads: 10
  map_threads: 6

# http://www.htslib.org/doc/samtools.html
samtools:
  sort:
    chunk_size: "4G"
    chunk_size_bigmem: "16G"


##############################
# Taxonomy workflow
# DIAMOND parameters
diamond:
  threads: 12

##############################
# Phage-host identification
phist:
  threads: 24

spacepharer:
  threads: 24

##############################
# AMR workflow
# https://github.com/arpcard/rgi
rgi:
  threads: 8
  db_url: "https://card.mcmaster.ca/latest/data"

