__default__:
  time: "0-01:00:00"
  partition: "batch"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""
  job-name: "nomis_virome.{rule}"


# Viruses
vibrant:
  time: "00-04:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""
