__default__:
  time: "0-01:00:00"
  partition: "batch"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""
  job-name: "nomis_virome.{rule}"


# Viruses
vibrant:
  time: "00-04:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""

mapping_index:
  time: "00-10:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""

mapping:
  time: "00-10:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""

summarise_depth:
  time: "00-12:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""

vamb:
  time: "00-12:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""

checkm:
  time: "02-00:00:00"
  partition: "bigmem"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""
